# Generated by Django 5.1.7 on 2025-03-21 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_securityprotocol_useraccountstatus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenVault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=36, unique=True)),
                ('encrypted_card_number', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'payments_tokenvault',
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='token',
            field=models.CharField(default='8403f31ea86b413c856f2cce1395548f', max_length=36, unique=True),
        ),
        migrations.AlterModelTable(
            name='transaction',
            table='payments_transaction',
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_text', models.TextField(max_length=200)),
                ('category', models.CharField(choices=[('Poor Service', 'Poor Service'), ('Account Issue', 'Account Issue'), ('Fraud', 'Fraud'), ('Monetary Issue', 'Monetary Issue')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complained_against', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints_against', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_complaints',
            },
        ),
    ]
