# Generated by Django 5.1.7 on 2025-03-21 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_transaction_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='token',
            field=models.CharField(default='ba5811d0c09d4cbc88360edd2c016bb0', max_length=36, unique=True),
        ),
    ]
