# Generated by Django 5.1.7 on 2025-03-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_remove_transaction_card_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='token',
            field=models.CharField(default='54bd10e9936c41f88b7f569674edcabf', max_length=36, unique=True),
        ),
    ]
