# Generated by Django 5.1.7 on 2025-03-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_transaction_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='token',
            field=models.CharField(default='608debd15ae8481996fb42dc7ca8cae0', max_length=36, unique=True),
        ),
    ]
