# Generated by Django 5.1.7 on 2025-03-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_alter_transaction_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='token',
            field=models.CharField(default='421627db225e4ca49b6c8fc06571e52a', max_length=36, unique=True),
        ),
    ]
