# Generated by Django 5.1.7 on 2025-03-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_alter_transaction_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='token',
            field=models.CharField(default='14d768fafe00468f8d290eb30f932ec5', max_length=36, unique=True),
        ),
    ]
