# Generated by Django 5.1.7 on 2025-03-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_alter_transaction_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='token',
            field=models.CharField(default='5939511dd9754ed5b60c1b941f6d0376', max_length=36, unique=True),
        ),
    ]
