# Generated by Django 5.1.7 on 2025-03-15 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_customertransaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerTransaction',
        ),
    ]
