# Generated by Django 5.1.7 on 2025-03-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_merchanttransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchanttransaction',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
