# Generated by Django 5.1.7 on 2025-03-21 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_tokenvault_transaction_token_alter_transaction_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='token',
            field=models.CharField(default='b40e9bfa48844dc6ad42051c1c4590f4', max_length=36, unique=True),
        ),
    ]
