# Generated by Django 5.1.7 on 2025-04-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_securityprotocol_useraccountstatus_tokenvault_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchanttransaction',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
