# Generated by Django 5.1.7 on 2025-03-21 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_transaction_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='card_number',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='token',
            field=models.CharField(default='fff13f9eebde4558bd6abf90f5e1b1e3', max_length=36, unique=True),
        ),
    ]
