# Generated by Django 5.1.7 on 2025-04-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_merchanttransaction_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchanttransaction',
            name='token',
        ),
        migrations.AddField(
            model_name='transaction',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
