# Generated by Django 5.2 on 2025-04-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_remove_merchanttransaction_token_transaction_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityProtocolDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
