# Generated by Django 5.1.7 on 2025-03-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_alter_transaction_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='token',
            field=models.CharField(default='43c92ae59cb2458a93770701b72273e0', max_length=36, unique=True),
        ),
    ]
