# Generated by Django 5.2 on 2025-04-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_securityprotocoldetail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='securityprotocoldetail',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='complaint',
            name='closing_comment',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='complaint_status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=50),
        ),
    ]
