# Generated by Django 5.1.7 on 2025-04-22 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_savedpaymentmethod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedpaymentmethod',
            name='expiry_month',
        ),
        migrations.RemoveField(
            model_name='savedpaymentmethod',
            name='expiry_year',
        ),
    ]
