# Generated by Django 5.1.7 on 2025-04-20 08:24

from django.db import migrations

from django.db import migrations
from payments.models import LegacyUser

def initialize_agents(apps, schema_editor):
    HelpdeskAgent = apps.get_model('payments', 'HelpdeskAgent')
    LegacyUser = apps.get_model('payments', 'LegacyUser')
    
    for user in LegacyUser.objects.filter(role_id=4):
        HelpdeskAgent.objects.get_or_create(user=user)

class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_helpdeskagent_message'),
    ]

    operations = [
        migrations.RunPython(initialize_agents),
    ]
