# Generated by Django 5.1.7 on 2025-03-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_alter_transaction_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='token',
            field=models.CharField(default='07b1d85c747949fc8a3b23be6d933761', max_length=36, unique=True),
        ),
    ]
