# Generated by Django 5.2 on 2025-04-28 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_alter_securityprotocoldetail_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='securityprotocoldetail',
            table='securityprotocoldetail',
        ),
    ]
