# Generated by Django 5.2 on 2025-04-29 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_remove_savedpaymentmethod_expiry_month_and_more'),
        ('payments', '0011_alter_securityprotocoldetail_table'),
    ]

    operations = [
    ]
