# Generated by Django 5.2 on 2025-04-29 08:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_merge_20250429_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchanttransaction',
            name='transaction_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='savedpaymentmethod',
            name='payment_type',
            field=models.CharField(choices=[('VISA', 'VISA'), ('MASTERCARD', 'MasterCard')], max_length=20),
        ),
    ]
