# Generated by Django 5.1.7 on 2025-04-10 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_alter_transaction_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='token',
            field=models.CharField(default='a33736ec468e4d58906e2760c56f664c', max_length=36, unique=True),
        ),
    ]
