# Generated by Django 5.1.7 on 2025-04-10 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_alter_transaction_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='token',
            field=models.CharField(default='b9a1efe1b9664d25b876e74a726e6ca9', max_length=36, unique=True),
        ),
    ]
