# Generated by Django 5.1.7 on 2025-04-10 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_alter_transaction_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='token',
            field=models.CharField(default='922b9098092345379e340db4a28ac192', max_length=36, unique=True),
        ),
    ]
