# Generated by Django 5.1.7 on 2025-04-10 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_alter_transaction_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='token',
            field=models.CharField(default='21658595180a48309c8bf2ec9775861a', max_length=36, unique=True),
        ),
    ]
