# Generated by Django 5.1.7 on 2025-04-10 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0019_alter_transaction_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='token',
            field=models.CharField(default='fa00ca426f4b43f99f49c61dce0192a7', max_length=36, unique=True),
        ),
    ]
