# Generated by Django 5.1.7 on 2025-04-10 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0020_alter_transaction_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='token',
            field=models.CharField(default='782dc9ad1cff4d95a45c173f89e705f3', max_length=36, unique=True),
        ),
    ]
