# Generated by Django 5.1.7 on 2025-04-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0021_alter_transaction_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='token',
            field=models.CharField(default='e869bf20f1ae490f89e3489184667d84', max_length=100, unique=True),
        ),
    ]
